apiVersion: v1
kind: Service
metadata:
  name: <SERVICE_NAME>
  namespace: <NAMESPACE_NAME>
spec:
  ports:
  - port: 80
    targetPort: <PORT>
  selector:
    <POD_KEY>: <POD_VALUE>
  clusterIP: None
